# This is the configuration used to check the rubocop source code.
#inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  Exclude:
    - 'config/initializers/*'
    - 'config/deploy/*'
    - 'config/deploy.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'lib/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120

Style/Encoding:
  EnforcedStyle: always
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Encoding:
  Enabled: false

Documentation:
  Enabled: false

Style/PredicateName:
  NamePrefix:
    - have_

RSpec/NestedGroups:
  Max: 4

RSpec/InstanceVariable:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/FilePath:
  Enabled: false